CC = clang         
CFLAGS = -O3 		
INC = -I .
# LIB = -L src/lib       
       
all: 
#	${CC} src/wavereader.c ${CFLAGS} ${INC} ${LIB} -o build/wavereader
	${CC} readwave.c ${CFLAGS} ${INC} -o readwav
clean:                             
	@rm -rf *.o  readwav